spring:
  datasource:
    url: jdbc:mariadb://desktop:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: backendjjn
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
